services:
  - type: web
    name: sbi-mf-rag-chatbot
    runtime: docker
    plan: free
    envVars:
      - key: CHROMA_API_KEY
        sync: false
      - key: CHROMA_TENANT
        sync: false
      - key: CHROMA_DATABASE
        sync: false
      - key: GROQ_API_KEY
        sync: false
